language: java
jdk:
  - openjdk11
before_script:
  - chmod +x SimpleArgumentParser/gradlew
script:
  - ./SimpleArgumentParser/gradlew check
  - ./SimpleArgumentParser/gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
